version: '3.4'

services:
  web:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_URLS=http://*:5000

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
